export const TYPES = [
  "Planet",
  "Cluster",
  "Space station",
  "Microverse",
  "TV",
  "Resort",
  "Fantasy town",
  "Dream",
  "Dimension",
  "Game",
  "Customs",
  "Daycare",
  "Dwarf planet",
  "Celestial Dwarf",
  "Teenyverse",
  "Miniverse",
  "Spacecraft",
  "Box",
  "Artificially generated world",
  "Machine",
  "Arcade",
  "Spa",
  "Quadrant",
  "Quasar",
  "Mount",
  "Liquid",
  "Convention",
  "Woods",
  "Diegesis",
  "Non-Diegetic",
  "Alternative Reality",
  "Nightmare",
  "Asteroid",
  "Acid Plant",
  "Reality",
  "Death Star",
  "Base",
  "Unknown",
];

export const DIMENSIONS = [
  "Dimension C-137",
  "Post-Apocalyptic",
  "Replacement",
  "Cronenberg",
  "Fantasy",
  "Dimension 5-126",
  "Testicle Monster",
  "Cromulon",
  "Dimension C-500A",
  "Dimension K-83",
  "Dimension J19ζ7",
  "Eric Stoltz Mask",
  "Evil Rick's Target",
  "Giant Telepathic",
  "Dimension K-22",
  "Dimension D-99",
  "Dimension D716",
  "Dimension D716-B",
  "Dimension D716-C",
  "Dimension J-22",
  "Dimension C-35",
  "Pizza Dimension",
  "Phone Dimension",
  "Chair Dimension",
  "Fascist Dimension",
  "Fascist Shrimp",
  "Fascist Teddy Bear",
  "Wasp Dimension",
  "Magic Dimension",
  "Merged Dimension",
  "Unknown",
];
